version: '3'
services:
  bot-storage:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dservices-storage
    restart: unless-stopped
    ports:
      - "3300:3300"
    networks:
      - global-network
    volumes:
      - .:/app
      - /app/node_modules
networks:
    global-network:
        external: true
